package destination

import (
	"bytes"
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"

	"feedrepeater.com/internal/safehttp"
)

// WebhookConfig is the non-secret half of a webhook destination.
type WebhookConfig struct {
	URL string `json:"url"`
}

// WebhookCredentials holds the signing secret. It is generated by this service,
// shown to the user once, and stored encrypted.
type WebhookCredentials struct {
	Secret string `json:"secret"`
}

// Signature header names.
const (
	HeaderSignature = "X-Feedrepeater-Signature"
	HeaderTimestamp = "X-Feedrepeater-Timestamp"
	HeaderDelivery  = "X-Feedrepeater-Delivery"
)

type webhookTarget struct {
	http   *safehttp.Client
	url    string
	secret string
}

// NewWebhook builds a webhook target from stored configuration.
func NewWebhook(hc *safehttp.Client, configJSON string, credentials []byte) (Target, error) {
	var cfg WebhookConfig
	if err := jsonConfig(configJSON, &cfg); err != nil {
		return nil, Permanent(err)
	}
	u, err := publicURL(hc, cfg.URL)
	if err != nil {
		return nil, err
	}
	var creds WebhookCredentials
	if err := json.Unmarshal(credentials, &creds); err != nil || creds.Secret == "" {
		return nil, Permanentf("webhook: no signing secret stored")
	}
	return &webhookTarget{http: hc, url: u.String(), secret: creds.Secret}, nil
}

// Limit is unlimited: the payload carries the full entry, and the recipient
// decides what to do with it.
func (t *webhookTarget) Limit(context.Context) int { return 0 }

// WebhookPayload is the JSON body delivered to a webhook.
type WebhookPayload struct {
	Event      string  `json:"event"`
	DeliveryID string  `json:"delivery_id"`
	Timestamp  string  `json:"timestamp"`
	Text       string  `json:"text"`
	Item       payload `json:"item"`
}

type payload struct {
	Title     string `json:"title"`
	URL       string `json:"url"`
	Summary   string `json:"summary"`
	Author    string `json:"author"`
	Published string `json:"published_at,omitempty"`
	FeedTitle string `json:"feed_title"`
	FeedURL   string `json:"feed_url"`
}

func (t *webhookTarget) Send(ctx context.Context, p Post) (*Result, error) {
	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	now := time.Now().UTC()
	body := WebhookPayload{
		Event:      "entry.published",
		DeliveryID: p.IdempotencyKey,
		Timestamp:  now.Format(time.RFC3339),
		Text:       p.Text,
		Item: payload{
			Title:     p.Item.Title,
			URL:       p.Item.URL,
			Summary:   p.Item.Summary,
			Author:    p.Item.Author,
			FeedTitle: p.Item.FeedTitle,
			FeedURL:   p.Item.FeedURL,
		},
	}
	if !p.Item.Published.IsZero() {
		body.Item.Published = p.Item.Published.UTC().Format(time.RFC3339)
	}

	raw, err := json.Marshal(body)
	if err != nil {
		return nil, Permanent(err)
	}

	ts := strconv.FormatInt(now.Unix(), 10)
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, t.url, bytes.NewReader(raw))
	if err != nil {
		return nil, Permanent(err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set(HeaderTimestamp, ts)
	req.Header.Set(HeaderDelivery, p.IdempotencyKey)
	req.Header.Set(HeaderSignature, "sha256="+Sign(t.secret, ts, raw))

	resp, err := t.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("webhook: %w", err)
	}
	defer resp.Body.Close()
	// Drain a bounded amount so the connection can be reused, and discard it:
	// nothing the endpoint returns is shown to the user.
	_, _ = safehttp.ReadLimited(resp.Body, 64<<10)

	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		return nil, statusError("webhook", resp.StatusCode, "")
	}
	return &Result{}, nil
}

// VerifyEndpoint proves that whoever is adding a webhook controls the address
// they gave.
//
// Without this the service is an open relay: anyone can sign up, point a
// webhook at a stranger's server, and have feedrepeater deliver requests there
// on a schedule. The SSRF guard keeps those requests on the public internet,
// which protects our own network and nobody else's.
//
// The endpoint has to echo a challenge back. That is trivial for someone who
// wrote the receiver and impossible for someone who merely knows a URL.
func VerifyEndpoint(ctx context.Context, hc *safehttp.Client, rawURL, secret string) error {
	u, err := publicURL(hc, rawURL)
	if err != nil {
		return err
	}

	challenge := make([]byte, 16)
	if _, err := rand.Read(challenge); err != nil {
		return err
	}
	token := hex.EncodeToString(challenge)

	now := time.Now().UTC()
	body, err := json.Marshal(map[string]string{
		"event":     "verification",
		"challenge": token,
		"timestamp": now.Format(time.RFC3339),
	})
	if err != nil {
		return err
	}

	ctx, cancel := context.WithTimeout(ctx, 15*time.Second)
	defer cancel()

	ts := strconv.FormatInt(now.Unix(), 10)
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(body))
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set(HeaderTimestamp, ts)
	req.Header.Set(HeaderSignature, "sha256="+Sign(secret, ts, body))

	resp, err := hc.Do(req)
	if err != nil {
		return fmt.Errorf("could not reach that address: %w", err)
	}
	defer resp.Body.Close()

	answer, err := safehttp.ReadLimited(resp.Body, 64<<10)
	if err != nil {
		return fmt.Errorf("that address returned too much data")
	}
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		return fmt.Errorf("that address answered %d", resp.StatusCode)
	}
	if !echoedChallenge(answer, token) {
		return fmt.Errorf("that address did not echo the challenge back")
	}
	return nil
}

// echoedChallenge accepts the token as a bare body or as a JSON field, so a
// receiver can answer in whichever way is least work.
func echoedChallenge(body []byte, token string) bool {
	if strings.TrimSpace(string(body)) == token {
		return true
	}
	var out struct {
		Challenge string `json:"challenge"`
	}
	if json.Unmarshal(body, &out) == nil && out.Challenge == token {
		return true
	}
	return false
}

// Sign computes the payload signature. The timestamp is inside the signed
// material so a captured request cannot be replayed later with a fresh one.
func Sign(secret, timestamp string, body []byte) string {
	mac := hmac.New(sha256.New, []byte(secret))
	mac.Write([]byte(timestamp))
	mac.Write([]byte("."))
	mac.Write(body)
	return hex.EncodeToString(mac.Sum(nil))
}
